parameters:
  - name: workingDirectory
    type: string
    default: ''
  - name: name
    type: string
    default: ''
  - name: displayName
    type: string
    default: ''
  - name: environment
    type: string
    default: ''
  - name: assetsDirectory
    type: string
    default: ''
  - name: siteId
    type: string
    default: ''
  - name: sitemapBaseUrl
    type: string
    default: ''
  - name: siteName
    type: string
    default: ''
  - name: context
    type: string
    default: ''
  - name: conditional
    type: boolean
    default: false

stages:
  - stage: Deploy${{ coalesce(parameters.name, 'Unknown') }}
    condition: or(not(${{ parameters.conditional }}), and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'), ne(variables['Build.Reason'], 'PullRequest')))
    displayName: ${{ coalesce(parameters.displayName, 'Unknown Deployment') }}
    jobs:
      - deployment: DeployNetlify
        displayName: Deploy to Netlify
        variables:
          - group: Netlify
        environment: ${{ coalesce(parameters.environment, 'Netlify Unknown') }}
        strategy:
          runOnce:
            deploy:
              steps:
                - download: none
                - checkout: self
                - template: ./tasks/install-node-step.yaml
                  parameters:
                    projectDirectory: ${{ parameters.workingDirectory }}
                - template: ./tasks/pwsh-step.yaml
                  parameters:
                    projectDirectory: ${{ parameters.workingDirectory }}
                    scriptFile: initialize.ps1
                - template: ./tasks/pwsh-step.yaml
                  parameters:
                    projectDirectory: ${{ parameters.workingDirectory }}
                    scriptFile: build.ps1
                    arguments: -SiteName "${{ parameters.siteName }}" -Context "${{ parameters.context }}"
                    env:
                      NETLIFY_AUTH_TOKEN: $(NETLIFY_AUTH_TOKEN)
                      NETLIFY_SITE_ID: ${{ parameters.siteId }}
                - template: ./tasks/pwsh-step.yaml
                  parameters:
                    projectDirectory: ${{ parameters.workingDirectory }}
                    scriptFile: deploy.ps1
                    arguments: -AssetsDirectory "${{ parameters.assetsDirectory }}" -SitemapBaseUrl "${{ parameters.sitemapBaseUrl }}" -Context "${{ parameters.context }}"
                    env:
                      NETLIFY_AUTH_TOKEN: $(NETLIFY_AUTH_TOKEN)
                      NETLIFY_SITE_ID: ${{ parameters.siteId }}
